version: "3"
services:
  frontend:
    image: todofrontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_HOST=backend
    depends_on:
      - "backend"
  backend:
    image: todobackend
    ports:
      - "3001:3001"
  tests:
    image: todotest
    environment:
      - FRONT_HOST=front
    depends_on:
      - "frontend"
      - "backend"
